transaction_manager/manager/urls.py
from django.conf.urls import url
from . import views	

app_name = 'manager'

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^log_in/$', views.log_in, name='log_in'),
	url(r'^log_out/$', views.log_out, name='log_out'),
	url(r'^register/$', views.register, name='register'),
	url(r'^add_transaction/$', views.add_transaction, name='add_transaction'),
	url(r'^categories/$', views.categories, name='categories'),
	url(r'^add_category/$', views.add_category, name='add_category'),
]

transaction_manager/transaction_manager/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^manager/', include('manager.urls')),
]

transaction_manager/manager/models.py
from django.contrib.auth.models import User
from django.db import models
from .validators import validate_transaction_name, validate_category_name


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=50, validators=[validate_category_name])

    def __str__(self):
        return self.name


class Transaction(models.Model):
    user = models.ForeignKey(User, default=1)
    name = models.CharField(max_length=100, validators=[validate_transaction_name])
    value = models.DecimalField(max_digits=6, decimal_places=2)
    category = models.ForeignKey(Category, default=1)

    def __str__(self):
        return self.name + ' - ' + str(self.value)

transaction_manager/manager/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Transaction, Category
from .validators import *

class RegisterForm(forms.ModelForm):

	username = forms.CharField(validators=[validate_username])
	password = forms.CharField(validators=[validate_password], widget=forms.PasswordInput)
	confirmation = forms.CharField(widget=forms.PasswordInput);

	class Meta:
		model = User
		fields = ['username', 'email', 'password']

	def clean(self):
		password = self.cleaned_data.get('password')
		confirmation = self.cleaned_data.get('confirmation')

		if password and password != confirmation:
			self.add_error("password", "Passwords don't match.")


class TransactionForm(forms.ModelForm):

	name = forms.CharField(validators=[validate_transaction_name])

	class Meta:
		model = Transaction
		fields = ['name', 'value', 'category']


class CategoryForm(forms.ModelForm):

	name = forms.CharField(validators=[validate_category_name])

	class Meta:
		model = Category
		fields = ['name']

transaction_manager/manager/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import loader
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from .forms import RegisterForm, TransactionForm, CategoryForm
from .models import Transaction, Category

def index(request) :
	if not request.user.is_authenticated():
		return redirect('/manager/log_in/')

	transactions = Transaction.objects.filter(user=request.user)
	return render(request, 'manager/index.html', {'transactions': transactions})


def log_in(request):
	
	if request.method != "POST":
		return render(request, 'manager/log_in.html')
		
	username = request.POST['username']
	password = request.POST['password']

	user = authenticate(username=username, password=password)

	if user is None:
		return render(request, 'manager/log_in.html', {'error_message': 'Invalid login/password.'})

	login(request, user)
	
	return index(request)

def log_out(request):
    logout(request)
    return redirect('/manager/log_in/')

def register(request):
	form = RegisterForm(request.POST or None)

	if form.is_valid():

		user = form.save(commit=False)

		username = form.cleaned_data['username']
		password = form.cleaned_data['password']
		user.set_password(password)

		user.save()

		user = authenticate(username=username, password=password)

		if user is not None:
			login(request, user)
			return index(request)

	return render(request, 'manager/register.html', {'form': form})


def add_transaction(request):
	if not request.user.is_authenticated():
		return redirect('/manager/log_in/')

	form = TransactionForm(request.POST or None)

	if form.is_valid():
		trans = form.save(commit=False)
		trans.user = request.user
		trans.save()
		return index(request)

	return render(request, 'manager/add_transaction.html', {'form': form})

def categories(request):
	if not request.user.is_authenticated():
		return redirect('/manager/log_in/')

	categories = Category.objects.all()
	return render(request, 'manager/categories.html', {'categories': categories})


def add_category(request):
		
	if not request.user.is_authenticated():
		return redirect('/manager/log_in/')

	form = CategoryForm(request.POST or None)

	if form.is_valid():
		category = form.save(commit=False)
		category.save()
		return categories(request)

	return render(request, 'manager/add_category.html', {'form': form})

transaction_manager/manager/templates/manager/add_category.html
{% extends 'manager/base.html' %}
{% block title %}New Category{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add Transaction Category</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'manager/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

transaction_manager/manager/templates/manager/add_transaction.html
{% extends 'manager/base.html' %}
{% block title %}New Transaction{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add Transaction</h3>
                    {% if error_message %}
                        <p class="error_message">{{ error_message }}</p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'manager/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

transaction_manager/manager/templates/manager/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Transaction Manager</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'manager:index' %}">Transaction Manager</a>
    </div>
  </div><!-- /.container-fluid -->
</nav>

{% block body %}
{% endblock %}

</body>
</html>

transaction_manager/manager/templates/manager/categories.html
{% extends 'manager/base.html' %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-8">
            <h2>Categories</h2>
        </div>
        <div class="col-sm-4">
            <a href="{% url 'manager:add_transaction' %}">
                <button type="button" class="btn btn-success">
                    <span class="glyphicon glyphicon-plus"></span>&nbsp; Add Transaction
                </button>
            </a>
            <a href="{% url 'manager:add_category' %}">
                <button type="button" class="btn btn-info">
                    <span class="glyphicon glyphicon-plus"></span>&nbsp; Add Category
                </button>
            </a>
            <a href="{% url 'manager:log_out' %}">
                <button type="button" class="btn btn-danger">
            &nbsp;
                    Logout
                </button>
            </a>
        </div>
        {% if categories %}
        <div class="col-sm-12">
            <table class="table">
                <thead>
                    <tr>
                        <th>Name</th>
                    </tr>
                </thead>
                <tbody>
		            {% for cat in categories %}
		            	<tr>
		            		<td>{{ cat.name }}</td>
		            	</tr>
		            {% endfor %}
                </tbody>
            </table>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

transaction_manager/manager/templates/manager/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

transaction_manager/manager/templates/manager/index.html
{% extends 'manager/base.html' %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-8">
            <h2>{{ user.username }}'s Transactions</h2>
        </div>
        <div class="col-sm-4">
            <a href="{% url 'manager:add_transaction' %}">
                <button type="button" class="btn btn-success">
                    <span class="glyphicon glyphicon-plus"></span>&nbsp; Add Transaction
                </button>
            </a>
            <a href="{% url 'manager:categories' %}">
                <button type="button" class="btn btn-info">
                    Categories
                </button>
            </a>
            <a href="{% url 'manager:log_out' %}">
                <button type="button" class="btn btn-danger">
            &nbsp;
                    Logout
                </button>
            </a>
        </div>
        {% if transactions %}
        <div class="col-sm-12">
            <table class="table">
                <thead>
                    <tr>
                        <th>Description</th>
                        <th>Value</th>
                        <th>Category</th>
                    </tr>
                </thead>
                <tbody>
		            {% for trans in transactions %}
		            	<tr>
		            		<td>{{ trans.name }}</td>
		            		<td>$ {{ trans.value }}</td>
                            <td>{{ trans.category }}</td>
		            	</tr>
		            {% endfor %}
                </tbody>
            </table>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

transaction_manager/manager/templates/manager/log_in.html
{% extends 'manager/base.html' %}
{% block title %}Log In{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p class="error-message">{{ error_message }}</p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'manager:log_in'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'manager:register' %}">Click here</a> to Register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

transaction_manager/manager/templates/manager/register.html
{% extends 'manager/base.html' %}
{% block title %}Register{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p class="error_message">{{ error_message }}</p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'manager/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Already have an account? <a href="{% url 'manager:log_in' %}">Click here</a> to Log In.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}